export default [{
  name: 'Model S',
  topSpeed: '1.99 0-100mph' ,
  engineBy: 'Engine Done by Tom Herry',
  text: 'l S is built from the ground up as an electric vehicle, with a high-strength architecture and floor-mounted battery pack for incredible occupant protection and low rollover risk. Every Model S includes Tesla’s latest active safety features, such as Automatic Emergency Braking, at no extra cost.',
  tagline: 'Starting at $69,420',
  image: require('../../assets/images/ModelS.jpeg'),
}, {
  name: 'Model 3',
  topSpeed: '0.3s 0-100mph' ,
  engineBy: 'Engine Done by Jhon Watson',
  text: 'Model 3 comes with the option of dual motor all-wheel drive, 20” Überturbine Wheels and Performance Brakes and lowered suspension for total control, in all weather conditions. And a carbon fiber spoiler improves stability at high speeds, all allowing Model 3 to accelerate from 0-60 mph* in as little as 3.1 seconds.',
  tagline: 'Order Online for',
  taglineCTA: 'Touchless Delivery',
  image: require('../../assets/images/Model3.jpeg'),
}, {
  name: 'Model X',
  topSpeed: '0.3s 0-100mph'   ,
  engineBy: 'Engine Done by Tom Hank',
  text: 'This car build with high end carbonfibre, Seat by Genuine leather, Authentic color',
  tagline: 'Order Online for',
  taglineCTA: 'Touchless Delivery',
  image: require('../../assets/images/ModelX.jpeg'),
}, {
  name: 'Model Y',
  topSpeed: '0.5s 0-100mph'   ,
  engineBy: 'Engine Done by Jhon Smith',
  text: 'This car build with high end carbonfibre, Seat by Genuine leather, Authentic color',
  tagline: 'Order Online for',
  taglineCTA: 'Touchless Delivery',
  image: require('../../assets/images/ModelY.jpeg'),
}];
